language: php

php:
  - 5.6
  - 7.0

env:
  global:
    - WP_VERSION=master

before_script:
  - composer install --prefer-source
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

cache:
  directories:
    - vendor/

notifications:
  email: false